### ISSUE TITLE
Can you check this?

### ISSUE THREAD

**Issue by ECarline** [Minion3665/forum#2]
[post.zip](https://github.com/Minion3665/forum/files/3659130/post.zip)

**Comment by Minion3665** [comment]
@UpgradeDenied 
This looks great. I just have a few things for you to consider
1) You didn't include the date or a post title.
2) The font, while it looks nice, is not great for accessibility. Remember, that when writing something you need it to be possible to read.
3) There may not be enough spacing or borders between some elements. Try using css margins, padding and borders to improve the formatting

**Comment by Minion3665** [comment]
@UpgradeDenied (forgot to mention you in the last post. Sorry if you get a double ping)

**Comment by ECarline** [comment]
Thanks I’ll make the improvements this morning

**Comment by ECarline** [comment]
[post revision 2.zip](https://github.com/Minion3665/forum/files/3665180/post.revision.2.zip)
